apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ed-beta
  name: ed-beta-deployment
  namespace: elpis-demo-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ed-beta-pod
  template:
    metadata:
      labels: 
        app: ed-beta-pod
    spec:
      containers:
        - image: 
          name: g-wfya7883-docker.pkg.coding.net/love-elpis/elpis-demo-007/elpis-demo-image-beta
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: coding-registry-cred-9234756